### PR TITLE
Alma 9 support

### PR DESCRIPTION
**Pull request by pasimko**

### CODE REVIEW

**Review by ramereth — CHANGES_REQUESTED** [review]
Please add Alma9 to spec tests and also update all `kitchen.*yml` files.

**Comment by pasimko** [comment]
Ignoring dokken being broken because of ```
         - package curl-minimal-7.76.1-29.el9_4.1.x86_64 from @System conflicts with curl provided by curl-7.76.1-29.el9_4.1.x86_64 from baseos
         - package curl-minimal-7.76.1-29.el9_4.1.x86_64 from baseos conflicts with curl provided by curl-7.76.1-29.el9_4.1.x86_64 from baseos
         - package curl-minimal-7.76.1-29.el9_4.x86_64 from baseos conflicts with curl provided by curl-7.76.1-29.el9_4.1.x86_64 from baseos```

**Comment by ramereth** [comment]
!bump patch ~

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a patch-level version bump to v2.1.3.  Have a nice day!

**Pull request merged**
